blank_issues_enabled: false

contact_links:
  - name: ğŸ¤– ğŠğ‘ğˆğ’ğ‡ğğ€â»ğğ€ğğ” Support
    url: https://github.com/radha8094/RK-KRISHNA-BRAND/issues
    about: Bug report, feature request aur help ke liye yahan issue banaye
